name: Deploy to Balena Fleet

# limit to a single build of this pipeline
# Cancel any previous builds in favor of this build
concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    #paths-ignore:   # do not run if these are the only files that have changed
    #  - .github/**

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      VERSION: 1.0.${{ github.run_number }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and deploy app with Balena CLI
        run: |
          set -euo pipefail
          
          url=$(.github/get_balena-cli_url.sh)
          curl -L -o /tmp/balena.zip ${url}
          unzip /tmp/balena.zip -d /opt
          rm /tmp/balena.zip
          export PATH=$PATH:/opt/balena-cli

          
          trap "balena logout" EXIT # be sure to log out when done

          balena login --token ${{secrets.BALENA_TOKEN}}
          
          balena push HeatPi
          balena push DroidJS #testing
    